name: Update VERSION file, recreate the tag, and release

on:
  push:
    tags:
      - '*'

jobs:
  update_version_and_retag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Extract current tag
        id: version
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
          echo "Current tag: $CURRENT_TAG"

      - name: Write current version to VERSION file
        run: echo $CURRENT_TAG > VERSION

      - name: Commit, delete old tag, recreate tag, and push
        run: |
          git config --local user.email "painter@3lines.club"
          git config --local user.name "Michael Gunkoff via GitHub Action"
          git add VERSION
          git commit -m "Update VERSION with current tag" || echo "No changes to commit"

          # Save the SHA of the new commit for later use
          NEW_COMMIT_SHA=$(git rev-parse HEAD)

          # Checkout the main branch and merge the changes from our new commit
          git checkout main
          git merge $NEW_COMMIT_SHA

          # Delete the old tag locally and remotely
          git tag -d $CURRENT_TAG
          git push --delete origin $CURRENT_TAG

          # Create the tag again, now pointing to the new commit
          git tag $CURRENT_TAG

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kaatinga/commit.git
          echo "Pushing changes, recreated tag to repository, and main branch"
          git push origin main
          git push origin $CURRENT_TAG

      - name: Update Draft to Release or Create GitHub Release
        run: |
          # Fetch release data for the current tag
          RESPONSE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                                -H "Accept: application/vnd.github.v3+json" \
                                https://api.github.com/repos/${{ github.repository }}/releases/tags/$CURRENT_TAG)
          RELEASE_ID=$(echo $RESPONSE_JSON | jq '.id')
          DRAFT_STATUS=$(echo $RESPONSE_JSON | jq '.draft')
          RELEASE_NAME=$(echo $RESPONSE_JSON | jq '.name')

          # If a release ID was found and it's a draft, update the release to non-draft
          if [[ "$RELEASE_ID" != "null" && "$DRAFT_STATUS" == "true" ]]; then
            curl -s -X PATCH \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID \
                 -d '{
                     "draft": false,
                     "name": '"$RELEASE_NAME"'
                   }'
          elif [[ "$RELEASE_ID" == "null" ]]; then
            # If no release was found, create a new release for the tag
            # (Note: Adjust the name as needed. For now, I'm retaining the original logic.)
            curl -s -X POST \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/releases \
                 -d '{
                     "tag_name": "'"$CURRENT_TAG"'",
                     "name": "'"$CURRENT_TAG"' Release",
                     "body": "Release for version '"$CURRENT_TAG"'",
                     "draft": false,
                     "prerelease": false
                   }'
          fi
      
      
