name: Update VERSION file

on:
  push:
    tags:
      - '*'

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Write current tag to file
        run: echo ${GITHUB_REF#refs/tags/} > VERSION

      - name: Commit and push
        run: |
          git config --local user.email "painter@3lines.club"
          git config --local user.name "Michael Gunkoff via GitHub Action"
          git add VERSION
          git commit -m "Update VERSION with current tag" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kaatinga/commit.git
          echo "Pushing to repository"
          git push origin ${{ github.ref }}
